/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author amabd7808
 */
public class Machine extends javax.swing.JFrame {

    /**
     * Creates new form Machine
     */
    public Machine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fries = new javax.swing.JLabel();
        numoffries = new javax.swing.JTextField();
        shawerma = new javax.swing.JLabel();
        numofshawerma = new javax.swing.JTextField();
        poutine = new javax.swing.JLabel();
        numofpoutine = new javax.swing.JTextField();
        falafel = new javax.swing.JLabel();
        numoffalafel = new javax.swing.JTextField();
        sushi = new javax.swing.JLabel();
        numofsushi = new javax.swing.JTextField();
        cola = new javax.swing.JLabel();
        numofcola = new javax.swing.JTextField();
        water = new javax.swing.JLabel();
        numofwater = new javax.swing.JTextField();
        total = new javax.swing.JLabel();
        grandprice = new javax.swing.JTextField();
        calculatetotal = new javax.swing.JButton();
        Donation = new javax.swing.JLabel();
        howmuch = new javax.swing.JLabel();
        donation = new javax.swing.JTextField();
        tax = new javax.swing.JLabel();
        taxresult = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        subtotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fries.setText("Fries ($4.99)");

        numoffries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numoffriesActionPerformed(evt);
            }
        });

        shawerma.setText("Shawerma ($4.99)");

        numofshawerma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numofshawermaActionPerformed(evt);
            }
        });

        poutine.setText("Poutine ($6.99)");

        numofpoutine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numofpoutineActionPerformed(evt);
            }
        });

        falafel.setText("Falafel ($0.29)l");

        sushi.setText("Sushi ($2.99)");

        cola.setText("Cola ($1.49)");

        water.setText("Water ($18.22)");

        total.setText("Total");

        grandprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grandpriceActionPerformed(evt);
            }
        });

        calculatetotal.setText("Calculate ");
        calculatetotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatetotalActionPerformed(evt);
            }
        });

        Donation.setText("Would you like to donate ??");

        howmuch.setText("How much?");

        tax.setText("Tax (13%)");

        jLabel1.setText("Subtotal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fries)
                    .addComponent(shawerma)
                    .addComponent(poutine)
                    .addComponent(falafel)
                    .addComponent(sushi)
                    .addComponent(cola)
                    .addComponent(water))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numofwater, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(numofcola)
                    .addComponent(numofsushi)
                    .addComponent(numoffalafel)
                    .addComponent(numofshawerma)
                    .addComponent(numoffries)
                    .addComponent(numofpoutine))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Donation)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(howmuch)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(donation))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calculatetotal)
                            .addGap(25, 25, 25)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tax)
                    .addComponent(total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(grandprice)
                    .addComponent(taxresult))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fries)
                            .addComponent(numoffries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shawerma)
                            .addComponent(numofshawerma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(poutine)
                            .addComponent(numofpoutine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(falafel)
                            .addComponent(numoffalafel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sushi)
                            .addComponent(numofsushi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cola)
                            .addComponent(numofcola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(water)
                            .addComponent(numofwater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Donation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(howmuch)
                            .addComponent(donation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(calculatetotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tax)
                    .addComponent(taxresult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total)
                    .addComponent(grandprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numofshawermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numofshawermaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numofshawermaActionPerformed

    private void numoffriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numoffriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numoffriesActionPerformed

    private void numofpoutineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numofpoutineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numofpoutineActionPerformed

    private void grandpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grandpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grandpriceActionPerformed

    private void calculatetotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatetotalActionPerformed
       // variable declaration area
        double one;
        double two;
        double three;
        double four;
        double five; 
        double six; 
        double seven;
        double nine;
        double priceall;
        double taxall;
        double totalsub;
        
        one = 4.99*Double.parseDouble(numoffries.getText());
        two = 4.99*Double.parseDouble(numofshawerma.getText());
        three = 6.99*Double.parseDouble(numofpoutine.getText());
        four = 0.29*Double.parseDouble(numoffalafel.getText());
        five = 2.99*Double.parseDouble(numofsushi.getText());
        six = 1.49*Double.parseDouble(numofcola.getText());
        seven = 18.22*Double.parseDouble(numofwater.getText());
        nine = Double.parseDouble(donation.getText());
        
        taxall=((one+two+three+four+five+six+seven)*0.13);
        totalsub=(one+two+three+four+five+six+seven+nine);
        priceall= taxall + totalsub;
        taxall= taxall * 100;
         taxall=Math.round(taxall);
         taxall= taxall/100;
         totalsub= totalsub * 100;
         totalsub=Math.round(totalsub);
         totalsub= totalsub/100;
         priceall= priceall * 100;
         priceall=Math.round(priceall);
         priceall= priceall/100;
        grandprice.setText(String.valueOf(priceall));
         taxresult.setText(String.valueOf(taxall));
          subtotal.setText(String.valueOf(totalsub));
    }//GEN-LAST:event_calculatetotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Machine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Donation;
    private javax.swing.JButton calculatetotal;
    private javax.swing.JLabel cola;
    private javax.swing.JTextField donation;
    private javax.swing.JLabel falafel;
    private javax.swing.JLabel fries;
    private javax.swing.JTextField grandprice;
    private javax.swing.JLabel howmuch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numofcola;
    private javax.swing.JTextField numoffalafel;
    private javax.swing.JTextField numoffries;
    private javax.swing.JTextField numofpoutine;
    private javax.swing.JTextField numofshawerma;
    private javax.swing.JTextField numofsushi;
    private javax.swing.JTextField numofwater;
    private javax.swing.JLabel poutine;
    private javax.swing.JLabel shawerma;
    private javax.swing.JTextField subtotal;
    private javax.swing.JLabel sushi;
    private javax.swing.JLabel tax;
    private javax.swing.JTextField taxresult;
    private javax.swing.JLabel total;
    private javax.swing.JLabel water;
    // End of variables declaration//GEN-END:variables
}
